Kbuild: fix build problem without SWITCHDEV
flower/qos_conf.o calls nfp_flower_cmsg_alloc which is defined by
flower/cmsg.o. It should be included into the build only when
CONFIG_NET_SWITCHDEV is enabled, otherwise kmods will trigger the following
linking error when CONFIG_NET_SWITCHDEV is disabled.

ERROR: "nfp_flower_cmsg_alloc" [...nfp-drv-kmods/src/nfp.ko] undefined!

Signed-off-by: Jiong Wang <jiong.wang@netronome.com>
Reviewed-by: Jakub Kicinski <jakub.kicinski@netronome.com>