compat: add support for OpenCloudOS
OpenCloudOS[1] kernel backports some changes that breaks our OOT
version check, it complains:

nfp_net_compat.h:1396:9: error: void value not ignored as it ought to be
  return bpf_map_inc(map, uref);
         ^~~~~~~~~~~~~~~~~~~~~~

And it's hard to distinguish if the target kernel is OpenCloudOS
or not like we do for Kylin or OpenEuler kernels due to the simple
content in its `utsrelease.h`:

define UTS_RELEASE "5.4.119-20.0009.20"

So now check the content in `include/linux/bpf.h` directly to
decide which function to call instead of using cumbersome version
check.

[1] https://docs.opencloudos.org/en/

Signed-off-by: Yinjun Zhang <yinjun.zhang@corigine.com>
Signed-off-by: Louis Peens <louis.peens@corigine.com>